[project]
name = "qatar-real-estate-bot"
version = "0.1.0"
dependencies = [
    "fastapi",
    "groq",
    "httpx",
    "supabase",
    "python-dotenv",
    "pydantic",
    "python-multipart",
    "openai",
    "anthropic",
    "google-api-python-client",
    "google-auth-httplib2",
    "google-auth-oauthlib"
]

[dependency-groups]
dev = [
    "workers-py"
]
